// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// set_ODE_Rcpp
List set_ODE_Rcpp(double t, arma::vec n, Rcpp::List parameters);
RcppExport SEXP RLumModel_set_ODE_Rcpp(SEXP tSEXP, SEXP nSEXP, SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type n(nSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type parameters(parametersSEXP);
    __result = Rcpp::wrap(set_ODE_Rcpp(t, n, parameters));
    return __result;
END_RCPP
}
// set_ODE_Rcpp_LM_OSL
List set_ODE_Rcpp_LM_OSL(double t, arma::vec n, Rcpp::List parameters);
RcppExport SEXP RLumModel_set_ODE_Rcpp_LM_OSL(SEXP tSEXP, SEXP nSEXP, SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type n(nSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type parameters(parametersSEXP);
    __result = Rcpp::wrap(set_ODE_Rcpp_LM_OSL(t, n, parameters));
    return __result;
END_RCPP
}
