#' This function translates the sequence (built by the user or parsed from  a *.seq file)
#' into simulation steps.
#' It detects automatically differences between single steps and simulates a heating/cooling step
#' up to the current stepo in the sequence
#'
#' @param sequence \code{\link{list}} : a list generated by \code{\link{read_SEQ2R}} or handmade
#'
#' @param n \code{\link{numeric}} (\bold{required}): concentration of electron-/holetraps, valence- and conductionband
#' from step before
#'
#' @param parms \code{\link{Rlum.Results object}} (\bold{required}):
#'
#' @param \dots further arguments and graphical parameters passed to
#' \code{\link{plot.default}}. See details for further information
#'
#' @return This function returns an RLum.Analysis object which can be analysed by further RLum functions.
#'
#' @note This function can do just nothing at the moment.
#'
#' @section Function version: 0.1.0
#'
#' @author Johannes Friedrich, University of Bayreuth (Germany),
#'
#' @references
#'
#' @seealso \code{\link{plot}}
#'
#' @examples
#'
#' #so far no example available
#'
#' @noRd
.translate_Sequence <- function(
  sequence,
  n,
  parms,
  txtProgressBar = TRUE
  ){

output.model <- list()

##terminal output for sequence progress
cat("\n[.translate_Sequence()] \n\t>> Simulate sequence \n")
##PROGRESS BAR
if(txtProgressBar){
  pb <- txtProgressBar(min=0,max=length(sequence), char = "=", style=3)
}

for (i in 1:length(sequence)){

  #check if temperatures of step before is lower than current sequence step and if step is not PH or CH
  #automatically heat to temperatrue of current sequence step
  if(((n@data$temp < sequence[[i]][1])&&(names(sequence)[i] != "PH")&&(names(sequence)[i] != "CH")) == TRUE){
    n <- .simulate_heating(temp_begin = n$temp,temp_end = sequence[[i]][1],b = 5,n,parms)
  }

  #check if temperature is lower than the step before
  #automatically cool to temperatrue of current sequence step
  if(n@data$temp > sequence[[i]][1]){
    n <- .simulate_heating(temp_begin = n$temp,temp_end = sequence[[i]][1], b = -5,n,parms)
  }

  #check if current sequence step is PH and if a holding time was submitted
  if((names(sequence)[i] == "PH")){
    if(length(sequence[[i]]) == 2){
      n <- .simulate_heating(temp_begin = n$temp,temp_end = sequence[[i]][1], b = 5,n,parms)
      n <- .simulate_pause(temp = sequence[[i]][1], duration = sequence[[i]][2], n, parms)
    }

    if (length(sequence[[i]]) >= 3){
      n <- .simulate_heating(temp_begin = n$temp,temp_end = sequence[[i]][1], b = sequence[[i]][3],n,parms)
      n <- .simulate_pause(temp = sequence[[i]][1], duration = sequence[[i]][2], n, parms)
    }
  }

  #check if current sequence step is CH and if a holding time was submitted
  if(names(sequence)[i] == "CH"){
    if(length(sequence[[i]]) == 2){
      n <- .simulate_heating(temp_begin = n$temp,temp_end = sequence[[i]][1], b = 5,n,parms)
      n <- .simulate_pause(temp = sequence[[i]][1], duration = sequence[[i]][2], n, parms)
    }

    if (length(sequence[[i]]) >= 3){
      n <- .simulate_heating(temp_begin = n$temp,temp_end = sequence[[i]][1], b = sequence[[i]][3],n,parms)
      n <- .simulate_pause(temp = sequence[[i]][1], duration = sequence[[i]][2], n, parms)
    }
  }

  #check if current sequence step is CW_OSL
  if(names(sequence)[i] == "OSL"){
    n <- .simulate_CW_OSL(temp = sequence[[i]][1],duration = sequence[[i]][2], optical_power = sequence[[i]][3],n,parms)
    output.model[[i]] <- n$CW_OSL.data
  }

  #check if current sequence step is ILL (illumination)
  if(names(sequence)[i] == "ILL"){
    n <- .simulate_illumination(temp = sequence[[i]][1],duration = sequence[[i]][2], optical_power = sequence[[i]][3],n,parms)

  }

  #check if current sequence step is LM_OSL
  if(names(sequence)[i] == "LM_OSL"){
    n <- .simulate_LM_OSL(temp = sequence[[i]][1],duration = sequence[[i]][2],n = n,parms = parms)
    output.model[[i]] <- n$LM_OSL.data
  }

  #check if current sequence step is TL
  if(names(sequence)[i] == "TL"){
    n <- .simulate_TL(temp_begin = sequence[[i]][1],temp_end = sequence[[i]][2],b = sequence[[i]][3],n,parms)
    output.model[[i]] <- n$TL.data
  }

  #check if current sequence step is IRR
  if(names(sequence)[i] == "IRR"){
    n <- .simulate_irradiation(temp = sequence[[i]][1], dose = sequence[[i]][2],DoseRate = sequence[[i]][3],n,parms)
    n <- .simulate_pause(temp = sequence[[i]][1], duration = 5, n, parms)
  }

  #check if current sequence step is IRR
  if(names(sequence)[i] == "RL" || names(sequence)[i] == "RF"){
    n <- .simulate_RL(temp = sequence[[i]][1], dose = sequence[[i]][2],DoseRate = sequence[[i]][3],n,parms)
    output.model[[i]] <- n$RF.data
    n <- .simulate_pause(temp = sequence[[i]][1], duration = 5, n, parms)
  }

  #check if current sequence step is PAUSE
  if(names(sequence)[i] == "PAUSE"){
    n <- .simulate_pause(temp = sequence[[i]][1], duration = sequence[[i]][2], n, parms)
  }

  ##update progress bar
  if (txtProgressBar) {
    setTxtProgressBar(pb, i)
  }


}

# delete null/empty entries in a list
output.model <- output.model[unlist(lapply(output.model,length)!=0)]

#return of the function is a "RLum.Analysis" object with the output of the given sequence
return(set_RLum(class = "RLum.Analysis", records = output.model))

}
